import React, { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useForm } from 'react-hook-form';
import {
  Dialog, DialogTitle, DialogContent, DialogActions, Button,
  TextField, Box, Typography, IconButton, Grid, InputAdornment, Divider
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import LocalShippingIcon from '@mui/icons-material/LocalShipping';
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutlined';
import { useData } from '../../contexts/DataContext';
import { formatTimestamp } from '../../utils/formatters';
import { gasApi } from '../../services/gasApi';
import { toast } from 'react-toastify';

const SectionLabel = ({ children }) => (
  <Typography variant="caption" fontWeight={700} color="text.secondary"
    sx={{ textTransform: 'uppercase', letterSpacing: '0.08em', mb: 1.5, display: 'block' }}>
    {children}
  </Typography>
);

export default function ArrangeLogisticsForm({ open, onClose, record, groupIds }) {
  const dispatch = useDispatch();
  const allRecords = useSelector((state) => state.workflow.records) || [];
  const { refresh, updateRow, headers, startSync, endSync } = useData();
  const [biltyFile, setBiltyFile] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const { register, handleSubmit, formState: { errors }, watch, setValue } = useForm({
    defaultValues: {
      transporterName: '',
      partyAddress: '',
      locationLink: '',
      vehicleNo: '',
      driverNo: '',
      biltyNo: '',
      biltyImage: null,
      transportingAmount: '',
    }
  });

  const biltyImageFile = watch('biltyImage');

  useEffect(() => {
    if (open && record) {
      setValue('partyAddress', record.partyAddress || '');
      setValue('locationLink', record.locationLink || '');
      setValue('transporterName', '');
      setValue('vehicleNo', '');
      setValue('driverNo', '');
      setValue('biltyNo', '');
      setValue('biltyImage', null);
      setValue('transportingAmount', '');
      setBiltyFile(null);
      setIsSubmitting(false);
    }
  }, [open, record, setValue]);

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setBiltyFile(file);
      setValue('biltyImage', { name: file.name, url: URL.createObjectURL(file) });
    }
  };

  const fileToBase64 = (file) => new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result);
    reader.onerror = error => reject(error);
  });

  const onSubmit = async (data) => {
    if (!record) return;
    const ids = groupIds?.length ? groupIds : [record.id];
    const matchedRecords = allRecords.filter(r => ids.includes(r.id));

    setIsSubmitting(true);
    if (startSync) startSync();
    let biltyImageUrl = '';
    const folderId = import.meta.env.VITE_FOLDER_BILTY;

    if (biltyFile && folderId) {
      try {
        const base64Data = await fileToBase64(biltyFile);
        const uploadRes = await gasApi.uploadFile({
          base64Data,
          fileName: biltyFile.name,
          mimeType: biltyFile.type,
          folderId,
        });
        if (uploadRes.success) {
          biltyImageUrl = uploadRes.fileUrl;
        }
      } catch (err) {
        console.error("Failed to upload Bilty image:", err);
        toast.warning("Failed to upload Bilty to Google Drive, proceeding without upload.");
      }
    }

    try {
      const headersList = headers?.logistics || [
        "Timestamp",
        "LN-Lift Number",
        "Indent No.",
        "Party Name",
        "Material Name",
        "Transporter Name",
        "Vehicle No.",
        "Driver No.",
        "Bilty No.",
        "Bilty Image",
        "Transporting Amount",
        "Party Address",
        "Party Location Link"
      ];

      const timestamp = formatTimestamp();

      const rowsData = matchedRecords.map(rec => {
        const rowObj = {
          "Timestamp": timestamp,
          "LN-Lift Number": "", // Will be generated by backend
          "Indent No.": rec.indentNumber,
          "Party Name": rec.partyName,
          "Material Name": rec.itemName,
          "Transporter Name": data.transporterName,
          "Vehicle No.": data.vehicleNo,
          "Driver No.": data.driverNo,
          "Bilty No.": data.biltyNo,
          "Bilty Image": biltyImageUrl || (biltyFile ? biltyFile.name : ''),
          "Transporting Amount": Number(data.transportingAmount) || 0,
          "Party Address": data.partyAddress,
          "Party Location Link": data.locationLink,
        };
        return headersList.map(h => rowObj[h] !== undefined ? rowObj[h] : "");
      });

      const result = await gasApi.batchInsertLogistics("LIFT-RECEIVED", rowsData);
      if (result.success && result.liftNumber) {
        // Update Actual3 in INDENT-PO
        for (const rec of matchedRecords) {
          await updateRow('indents', rec.id, {
            "Actual3": timestamp
          }, false);
        }

        toast.success(`Logistics arranged! Lift Number ${result.liftNumber} generated.`);
        await refresh(['indents', 'logistics'], false);
        onClose();
      } else {
        throw new Error(result.error || "Logistics batch insert failed");
      }
    } catch (err) {
      console.error("Failed to save logistics:", err);
      toast.error(err.message || "Failed to save logistics details to database.");
    } finally {
      setIsSubmitting(false);
      if (endSync) endSync();
    }
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth
      PaperProps={{ sx: { borderRadius: 3, maxHeight: '92vh' } }}>

      <DialogTitle sx={{ px: 3, py: 2, display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: 1, borderColor: 'divider' }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
          <Box>
            <Typography variant="subtitle1" fontWeight={700} sx={{ lineHeight: 1.2 }}>Arrange Logistics</Typography>
            {record && (
              <Typography variant="caption" color="text.secondary">
                {record.poNumber} · {record.partyName}
                {(groupIds?.length || 0) > 1 ? ` · ${groupIds.length} items` : ''}
              </Typography>
            )}
          </Box>
        </Box>
        <IconButton onClick={onClose} size="small"><CloseIcon fontSize="small" /></IconButton>
      </DialogTitle>

      <Box component="form" id="logistics-form" onSubmit={handleSubmit(onSubmit)}>
        <DialogContent sx={{ px: 3, py: 2.5, overflowY: 'auto' }}>
          <SectionLabel>Logistics Details</SectionLabel>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2.5 }}>
            <Grid container spacing={2.5}>
              <Grid item xs={4}>
                <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                  Transporter Name <span style={{ color: 'red' }}>*</span>
                </Typography>
                <TextField fullWidth size="small"
                  {...register('transporterName', { required: 'Required' })}
                  error={!!errors.transporterName} helperText={errors.transporterName?.message} />
              </Grid>
              <Grid item xs={4}>
                <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                  Vehicle No. <span style={{ color: 'red' }}>*</span>
                </Typography>
                <TextField fullWidth size="small"
                  {...register('vehicleNo', { required: 'Required' })}
                  error={!!errors.vehicleNo} helperText={errors.vehicleNo?.message} />
              </Grid>
              <Grid item xs={4}>
                <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                  Driver No. <span style={{ color: 'red' }}>*</span>
                </Typography>
                <TextField fullWidth size="small" type="tel"
                  {...register('driverNo', { required: 'Required' })}
                  error={!!errors.driverNo} helperText={errors.driverNo?.message} />
              </Grid>

              <Grid item xs={4}>
                <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                  Bilty No. <span style={{ color: 'red' }}>*</span>
                </Typography>
                <TextField fullWidth size="small"
                  {...register('biltyNo', { required: 'Required' })}
                  error={!!errors.biltyNo} helperText={errors.biltyNo?.message} />
              </Grid>
              <Grid item xs={4}>
                <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                  Transporting Amount
                </Typography>
                <TextField fullWidth size="small" type="number"
                  InputProps={{ startAdornment: <InputAdornment position="start">₹</InputAdornment> }}
                  {...register('transportingAmount')} />
              </Grid>
              <Grid item xs={4}>
                <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                  Party Location Link
                </Typography>
                <TextField fullWidth size="small"
                  {...register('locationLink')} />
              </Grid>

              <Grid item xs={8}>
                <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                  Party Address <span style={{ color: 'red' }}>*</span>
                </Typography>
                <TextField fullWidth size="small" multiline rows={2}
                  {...register('partyAddress', { required: 'Required' })}
                  error={!!errors.partyAddress} helperText={errors.partyAddress?.message} />
              </Grid>
              <Grid item xs={4}>
                <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                  Bilty Image (Optional)
                </Typography>
                <input accept="image/*,.pdf" style={{ display: 'none' }} id="arrange-bilty-upload" type="file" onChange={handleFileChange} />
                <label htmlFor="arrange-bilty-upload">
                  <Box sx={{
                    border: '2px dashed', borderColor: biltyImageFile ? 'success.main' : 'divider',
                    borderRadius: 2, p: 1, textAlign: 'center', cursor: 'pointer',
                    bgcolor: biltyImageFile ? 'success.50' : 'grey.50',
                    height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'center',
                    transition: 'all 0.2s ease',
                    '&:hover': { borderColor: 'primary.main', bgcolor: 'primary.50' }
                  }}>
                    {biltyImageFile ? (
                      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 1 }}>
                        <CheckCircleOutlineIcon sx={{ color: 'success.main', fontSize: 20 }} />
                        <Typography variant="body2" fontWeight={600} color="success.main" noWrap sx={{ maxWidth: '100px' }}>{biltyImageFile.name}</Typography>
                      </Box>
                    ) : (
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        <CloudUploadIcon sx={{ fontSize: 20, color: 'text.disabled' }} />
                        <Typography variant="body2" color="text.secondary" fontWeight={500}>Upload Bilty</Typography>
                      </Box>
                    )}
                  </Box>
                </label>
              </Grid>
            </Grid>
          </Box>
        </DialogContent>

        <DialogActions sx={{ px: 3, py: 2, borderTop: 1, borderColor: 'divider', gap: 1 }}>
          <Button onClick={onClose} variant="outlined" color="inherit" sx={{ minWidth: 110, height: 38 }}>Cancel</Button>
          <Button type="submit" form="logistics-form" variant="contained" color="success" disabled={isSubmitting} sx={{ minWidth: 150, height: 38 }}>
            {isSubmitting ? 'Saving...' : 'Save & Submit'}
          </Button>
        </DialogActions>
      </Box>
    </Dialog>
  );
}
