import React, { useState } from 'react';
import { useSelector } from 'react-redux';
import { useForm, Controller } from 'react-hook-form';
import {
  Dialog, DialogTitle, DialogContent, DialogActions, Button,
  TextField, Box, Typography, IconButton, Grid, RadioGroup,
  FormControlLabel, Radio, FormControl, FormLabel, Divider, CircularProgress
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutlined';
import Inventory2OutlinedIcon from '@mui/icons-material/Inventory2Outlined';
import { useData } from '../../contexts/DataContext';
import { gasApi } from '../../services/gasApi';
import { generateLiftNumber, formatDate } from '../../utils/formatters';
import { toast } from 'react-toastify';

const SectionLabel = ({ children }) => (
  <Typography variant="caption" fontWeight={700} color="text.secondary"
    sx={{ textTransform: 'uppercase', letterSpacing: '0.08em', mb: 1.5, display: 'block' }}>
    {children}
  </Typography>
);

export default function ReceiveMaterialForm({ open, onClose, record, groupIds }) {
  const allRecords = useSelector((state) => state.workflow.records) || [];
  const { receiving, refresh, addRow, headers } = useData();
  const [billFile, setBillFile] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const { register, handleSubmit, formState: { errors }, watch, setValue, control } = useForm({
    defaultValues: {
      productName: record?.itemName || '',
      quantity: record?.quantity || '',
      billNo: '',
      billImage: null,
      qualityCondition: 'Good',
    }
  });

  const billImageFile = watch('billImage');

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setBillFile(file);
      setValue('billImage', { name: file.name, url: URL.createObjectURL(file) });
    }
  };

  const fileToBase64 = (file) => new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result);
    reader.onerror = error => reject(error);
  });

  const onSubmit = async (data) => {
    if (!record) return;
    const ids = groupIds?.length ? groupIds : [record.id];
    const matchedRecords = allRecords.filter(r => ids.includes(r.id));

    setIsSubmitting(true);
    let billImageUrl = '';
    const folderId = import.meta.env.VITE_GOOGLE_DRIVE_FOLDER_ID;

    if (billFile && folderId) {
      try {
        const base64Data = await fileToBase64(billFile);
        const uploadRes = await gasApi.uploadFile({
          base64Data,
          fileName: billFile.name,
          mimeType: billFile.type,
          folderId,
        });
        if (uploadRes.success) {
          billImageUrl = uploadRes.fileUrl;
        }
      } catch (err) {
        console.error("Failed to upload bill image:", err);
        toast.warning("Failed to upload bill image to Google Drive, proceeding without upload.");
      }
    }

    try {
      let liftNo = record?.liftNo || record?.liftNumber;

      if (!liftNo) {
        // Direct receiving: Insert skeletal logistics row to generate unique lift number safely on backend
        const timestamp = formatDate(new Date());
        const headersList = headers?.logistics || [
          "Timestamp",
          "LN-Lift Number",
          "Indent No.",
          "Party Name",
          "Material Name",
          "Transporter Name",
          "Vehicle No.",
          "Driver No.",
          "Bilty No.",
          "Bilty Image",
          "Transporting Amount",
          "Party Address",
          "Party Location Link"
        ];

        const logisticsRows = matchedRecords.map(rec => {
          const rowObj = {
            "Timestamp": timestamp,
            "LN-Lift Number": "", // Generated by backend
            "Indent No.": rec.indentNumber,
            "Party Name": rec.partyName,
            "Material Name": rec.itemName,
            "Transporter Name": "Direct Receiving",
            "Vehicle No.": "Direct",
            "Driver No.": "Direct",
            "Bilty No.": "Direct",
            "Bilty Image": "",
            "Transporting Amount": 0,
            "Party Address": "Direct",
            "Party Location Link": ""
          };
          return headersList.map(h => rowObj[h] !== undefined ? rowObj[h] : "");
        });

        const logResult = await gasApi.batchInsertLogistics("LIFT-RECEIVED", logisticsRows);
        if (!logResult.success || !logResult.liftNumber) {
          throw new Error("Failed to generate Lift Number for Direct Receiving");
        }
        liftNo = logResult.liftNumber;
      }

      // Loop sequentially to write each receiving row
      for (const rec of matchedRecords) {
        const itemQty = matchedRecords.length === 1 ? Number(data.quantity) : rec.quantity;
        
        await addRow("receiving", {
          "Lift No.": liftNo,
          "Indent No.": rec.indentNumber,
          "Party Name": rec.partyName,
          "Product Name": rec.itemName,
          "Qty": itemQty,
          "Product Name2": "",
          "Qty2": "",
          "Product Name3": "",
          "Qty3": "",
          "Product Name4": "",
          "Qty4": "",
          "Product Name5": "",
          "Qty5": "",
          "Bill No.": data.billNo,
          "Quality Check": data.qualityCondition,
          "Bill Image": billImageUrl || (billFile ? billFile.name : ''),
          "lift Status": "Pending",
          "Status": "Pending"
        });
      }

      toast.success(`Material received! ${matchedRecords.length} item(s) moved to Lift Receiver.`);
      await refresh();
      onClose();
    } catch (err) {
      console.error("Failed to receive material:", err);
      toast.error(err.message || "Failed to record receiving verification in database.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth={false}
      PaperProps={{
        sx: {
          borderRadius: 3,
          width: '800px',
          maxWidth: '96vw',
          maxHeight: '92vh',
        }
      }}
    >
      {/* ── Header ── */}
      <DialogTitle sx={{ px: 3, py: 2, display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: 1, borderColor: 'divider' }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
          <Box sx={{ width: 38, height: 38, borderRadius: 2, bgcolor: 'info.50', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Inventory2OutlinedIcon sx={{ color: 'info.main', fontSize: 20 }} />
          </Box>
          <Box>
            <Typography variant="subtitle1" fontWeight={700} sx={{ lineHeight: 1.2 }}>Receive Material Verification</Typography>
            {record && (
              <Typography variant="caption" color="text.secondary">Indent: {record.indentNumber} &nbsp;·&nbsp; {record.itemName}</Typography>
            )}
          </Box>
        </Box>
        <IconButton onClick={onClose} size="small"><CloseIcon fontSize="small" /></IconButton>
      </DialogTitle>

      <Box component="form" id="receive-form" onSubmit={handleSubmit(onSubmit)}>
        <DialogContent sx={{ px: 3, py: 2.5, overflowY: 'auto' }}>

          {/* Section 1: Material Info */}
          <SectionLabel>Material Information</SectionLabel>
          <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 2.5, mb: 3 }}>
            <Box>
              <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                Product Name
              </Typography>
              <TextField fullWidth
                value={record?.itemName || ''}
                InputProps={{ readOnly: true }}
                sx={{ bgcolor: 'action.hover', '& input': { color: 'text.secondary', fontWeight: 600 } }}
              />
            </Box>
            <Box>
              <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                Quantity <span style={{ color: 'red' }}>*</span>
              </Typography>
              <TextField fullWidth type="number"
                {...register('quantity', { required: 'Required' })}
                error={!!errors.quantity} helperText={errors.quantity?.message} />
            </Box>
          </Box>

          <Divider sx={{ mb: 2.5 }} />

          {/* Section 2: Bill & Quality */}
          <SectionLabel>Bill & Quality Details</SectionLabel>
          <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 2.5, mb: 3 }}>
            <Box>
              <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                Bill No. <span style={{ color: 'red' }}>*</span>
              </Typography>
              <TextField fullWidth
                {...register('billNo', { required: 'Required' })}
                error={!!errors.billNo} helperText={errors.billNo?.message} />
            </Box>
            <Box>
              <Typography variant="body2" fontWeight={600} color="text.secondary" sx={{ mb: 0.5 }}>
                Quality Condition <span style={{ color: 'red' }}>*</span>
              </Typography>
              <FormControl component="fieldset" error={!!errors.qualityCondition} sx={{ width: '100%' }}>
                <Controller
                  name="qualityCondition"
                  control={control}
                  rules={{ required: 'Required' }}
                  render={({ field }) => (
                    <RadioGroup row {...field}>
                      <FormControlLabel value="Good" control={<Radio size="small" color="success" />} label={<Typography variant="body2">Good</Typography>} />
                      <FormControlLabel value="Average" control={<Radio size="small" color="warning" />} label={<Typography variant="body2">Average</Typography>} />
                      <FormControlLabel value="Bad" control={<Radio size="small" color="error" />} label={<Typography variant="body2">Bad</Typography>} />
                    </RadioGroup>
                  )}
                />
              </FormControl>
            </Box>
          </Box>

          <Divider sx={{ mb: 2.5 }} />

          {/* Section 3: Bill Upload */}
          <SectionLabel>Bill Document</SectionLabel>
          <input accept="image/*,.pdf" style={{ display: 'none' }} id="bill-file-upload" type="file" onChange={handleFileChange} />
          <label htmlFor="bill-file-upload">
            <Box sx={{
              border: '2px dashed', borderColor: billImageFile ? 'success.main' : 'divider',
              borderRadius: 2, p: 2.5, textAlign: 'center', cursor: 'pointer',
              bgcolor: billImageFile ? 'success.50' : 'grey.50',
              transition: 'all 0.2s ease',
              '&:hover': { borderColor: 'primary.main', bgcolor: 'primary.50' }
            }}>
              {billImageFile ? (
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 1 }}>
                  <CheckCircleOutlineIcon sx={{ color: 'success.main' }} />
                  <Typography variant="body2" fontWeight={600} color="success.main">{billImageFile.name}</Typography>
                </Box>
              ) : (
                <>
                  <CloudUploadIcon sx={{ fontSize: 32, color: 'text.disabled', mb: 0.5 }} />
                  <Typography variant="body2" color="text.secondary" fontWeight={500}>Click to upload Bill Image</Typography>
                  <Typography variant="caption" color="text.disabled">JPG, PNG, PDF accepted</Typography>
                </>
              )}
            </Box>
          </label>

        </DialogContent>

        {/* ── Footer ── */}
        <DialogActions sx={{ px: 3, py: 2, borderTop: 1, borderColor: 'divider', gap: 1 }}>
          <Button onClick={onClose} variant="outlined" color="inherit" sx={{ minWidth: 110, height: 38 }}>Cancel</Button>
          <Button type="submit" form="receive-form" variant="contained" color="primary" disabled={isSubmitting} sx={{ minWidth: 150, height: 38 }}>
            {isSubmitting ? 'Saving...' : 'Save & Submit'}
          </Button>
        </DialogActions>
      </Box>
    </Dialog>
  );
}
